### ISSUE TITLE
Distro/compiler compatibility 

### ISSUE THREAD

**Issue by erikfrojdh** [paulscherrerinstitute/slsDetector#1]
**Issue:** 

The pre-built shared libraries that are included in the repo doesn't work with all compilers/distros. 

**Proposed solution:** 

Add a note in the readme about this together with instructions how to build the slsDetectorPackage 

```bash
git clone https://github.com/slsdetectorgroup/slsDetectorPackage.git —branch=8.0.1
mkdir build && cd build
cmake .. -DSLS_USE_RECEIVER=OFF -DSLS_USE_RECEIVER_BINARIES=OFF -DSLS_USE_TEXTCLIENT=OFF
cmake --build .  -j8
```

**Comment by xiaoqiangwang** [comment]
Thanks for bringing this up. Last week I found this issue when using the RHEL7-prebuilt libraries on RHEL8. I haven't got time to look at it in detail yet. On which distro did you see the problem?

Sure a warning like this is required.

**Comment by erikfrojdh** [comment]
This particular case was with AlamLinux9, and gcc 11.4.1. Found by our colleagues at ANSTO

**Comment by xiaoqiangwang** [comment]
For information, [this article](https://developers.redhat.com/blog/2020/10/08/migrating-c-and-c-applications-from-red-hat-enterprise-linux-version-7-to-version-8) explains this C++ ABI breakage, see section *C++ ABI incompatibility between RHEL 7 and RHEL 8*

The way forward is to build current slsDetectorPackage on RHEL8. But it also requires updating detector server/firmware to match with the new version.

**Comment by xiaoqiangwang** [comment]
e2c266d updates the bundled slsDetector library to 8.0.2, which is built on RHEL8. The building process is described here,
https://github.com/paulscherrerinstitute/slsDetector/tree/main/slsDetectorApp/slsDetectorSupport/README.
